version: '3'
services:
  api:
    build: .
    image: api:latest
    container_name: api
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/usersdb
    depends_on:
      - mongo
    networks:
      - project-network

  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  mongo-data: